spring:
  application:
    name: demo


  datasource:
    url: jdbc:mysql://localhost:3306/nusteamproject1
    username: root
    password: 1234

mybatis:
  configuration:
    map-underscore-to-camel-case: true



