spring:
  application:
    name: demo


  datasource:
    url: jdbc:mysql://mysql:3306/cicd_for_test
    username: root
    password: 123456

mybatis:
  configuration:
    map-underscore-to-camel-case: true

