# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Maven Project

on:
  push:
    branches:
      - CiCD_Tester_YaoHaihan

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: myEmotion
          path: target/*.jar

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: myEmotion
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Transfer artifacts to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "*.jar"
          target: "/home/ubuntu/ec2"

      - name: Run Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/ec2
            docker-compose down
            docker-compose up --build --force-recreate -d

