name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build Maven Project"]
    types:
      - completed

jobs:
  deploy:
    needs: [Build Maven Project]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: myEmotion
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Transfer artifacts to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "*.jar"
          target: "/home/ubuntu/ec2"

      - name: Run Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/ec2
            docker-compose down
            docker-compose up --build --force-recreate -d

  # 新增的独立任务 "hello-world"
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
