# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - CiCD_Tester_YaoHaihan

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven
      
    - name: Build with Maven
      run: mvn clean package

    - name: Check current directory and list files
      run: |
        pwd
        ls -l

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /var/lib/docker
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Run Docker Compose
      run: |
        docker-compose down
        docker-compose up --build --force-recreate -d
      working-directory: .  # 确保Docker Compose在项目根目录运行
