# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - CiCD_Tester_YaoHaihan

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build with Maven
      run: mvn clean package

    - name: Run Docker Compose
      run: docker-compose up -d
      working-directory: .  # 确保Docker Compose在项目根目录运行

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
